Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.provider "virtualbox" do |v|
    v.name = "webapp_vm"
    # v.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "1"]
    v.memory = 1024
    v.cpus = 1
  end
end