global:
  scrape_interval:     5s
  evaluation_interval: 5s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'devopsapp'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'devopsapp:8000' ]

  - job_name: 'grafana'
    scrape_interval: 10s
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'loki'
    scrape_interval: 10s
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'promtail'
    scrape_interval: 10s
    static_configs:
      - targets: ['promtail:9080']
