apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devopsapp
  template:
    metadata:
      labels:
        app: devopsapp
    spec:
      containers:
      - name: devopsapp
        image: cendien/devopsapp:latest
        ports:
        - containerPort: 8000