apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devopsapp-chart.fullname" . }}
  labels:
    {{- include "devopsapp-chart.labels" . | nindent 4 }}
data:
  config.json: |-
    {{ .Files.Get "files/config.json" | nindent 4}}