apiVersion: v1
kind: Secret
metadata:
  name: credentials
  labels:
    app: devopsapp-chart
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
type: Opaque
